### ISSUE TITLE
Unknown dialyzer command line option on Elixir 1.7-dev

### ISSUE THREAD

**Issue by AndrewDryga** [jeremyjh/dialyxir#200]
When running on the local environment I get this error:
```
:dialyzer.run error: Unknown dialyzer command line option: {explain,nil}
```

Version RC2

Elixir/Erlang:
```
Erlang/OTP 20 [erts-9.3.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.7.0-dev (094eb6a) (compiled with Erlang/OTP 20)
```

**Comment by asummers** [comment]
How did you invoke the task there, out of curiosity? That should obviously be a much more helpful error, but I'm not even sure how you made it do that at first glance.

**Comment by jeremyjh** [comment]
—explain is not an option, you need to run ‘mix dialyzer.explain’

**Comment by AndrewDryga** [comment]
Here is what I run:
```
$ MIX_ENV=test mix dialyzer 
Finding suitable PLTs
Checking PLT...
[:asn1, :compiler, :connection, :cowboy, :cowlib, :crypto, :db_connection, :decimal, :ecto, :eex, :elixir, :myapp_domain, :inets, :jason, :kernel, :libcluster, :logger, :logger_json, :mime, :mix, :phoenix, :phoenix_ecto, :phoenix_pubsub, :plug, :poolboy, :postgrex, :public_key, :ranch, :ssl, :stdlib, :talkinto_domain]
PLT is up to date!
Starting Dialyzer
[
  check_plt: false,
  init_plt: '/Users/andrew/Projects/myapp/mono/_build/test/dialyxir_erlang-20.3.7_elixir-1.7.0-dev_deps-test.plt',
  files_rec: ['/Users/andrew/Projects/myapp/mono/_build/test/lib/myapp_web/ebin',
   '/Users/andrew/Projects/myapp/mono/_build/test/lib/talkinto_api/ebin',
   '/Users/andrew/Projects/myapp/mono/_build/test/lib/talkinto_domain/ebin',
   '/Users/andrew/Projects/myapp/mono/_build/test/lib/myapp_domain/ebin',
   '/Users/andrew/Projects/myapp/mono/_build/test/lib/mono_releases/ebin'],
  warnings: [:unmatched_returns, :error_handling, :race_conditions, :underspecs,
   :unknown],
  explain: nil,
  format: nil,
  raw: nil,
  list: nil
]
:dialyzer.run error: Unknown dialyzer command line option: {explain,nil}
```

**Comment by asummers** [comment]
Interesting. And you were not experiencing this behavior on 1.6.x?

**Comment by asummers** [comment]
Ah I see what's up. Fixing now.

**Comment by asummers** [comment]
Should be fixed in #201

**Comment by jeremyjh** [comment]
I'm guessing this is a consequence of `[OptionParser] Deprecate dynamic option parser mode that depended on atoms to be previously loaded and therefore behaved inconsistently`. I'm not sure its intended.

**Comment by AndrewDryga** [comment]
@asummers @jeremyjh I've updated to master but the issue persists:
```
$ mix dialyzer
Finding suitable PLTs
Checking PLT...
[:asn1, :compiler, :connection, :cowboy, :cowlib, :crypto, :db_connection, :decimal, :ecto, :eex, :elixir, :eview, :ex_machina, :hammer_domain, :inets, :jason, :kernel, :libcluster, :logger, :logger_json, :mime, :mix, :phoenix, :phoenix_ecto, :phoenix_pubsub, :plug, :poolboy, :postgrex, :public_key, :ranch, :ssl, :stdlib, :talkinto_domain]
PLT is up to date!
Starting Dialyzer
[
  check_plt: false,
  init_plt: '/Users/andrew/Projects/hammer/mono/_build/test/dialyxir_erlang-21.0.1_elixir-1.7.0-dev_deps-test.plt',
  files_rec: ['/Users/andrew/Projects/hammer/mono/_build/test/lib/hammer_web/ebin',
   '/Users/andrew/Projects/hammer/mono/_build/test/lib/talkinto_api/ebin',
   '/Users/andrew/Projects/hammer/mono/_build/test/lib/talkinto_domain/ebin',
   '/Users/andrew/Projects/hammer/mono/_build/test/lib/hammer_domain/ebin',
   '/Users/andrew/Projects/hammer/mono/_build/test/lib/mono_releases/ebin'],
  warnings: [:unmatched_returns, :error_handling, :race_conditions, :underspecs,
   :unknown],
  explain: nil,
  format: nil,
  raw: nil,
  list: nil
]
Starting Dialyzer
[
  check_plt: false,
  init_plt: '/Users/andrew/Projects/hammer/mono/_build/test/dialyxir_erlang-21.0.1_elixir-1.7.0-dev_deps-test.plt',
  files_rec: ['/Users/andrew/Projects/hammer/mono/_build/test/lib/hammer_web/ebin',
   '/Users/andrew/Projects/hammer/mono/_build/test/lib/talkinto_api/ebin',
   '/Users/andrew/Projects/hammer/mono/_build/test/lib/talkinto_domain/ebin',
   '/Users/andrew/Projects/hammer/mono/_build/test/lib/hammer_domain/ebin',
   '/Users/andrew/Projects/hammer/mono/_build/test/lib/mono_releases/ebin'],
  warnings: [:unmatched_returns, :error_handling, :race_conditions, :underspecs,
   :unknown],
  explain: nil,
  list: nil
]
:dialyzer.run error: Unknown dialyzer command line option: {explain,nil}
```

(Also you can see that it's started for 2 times for some reason.)

**Comment by AndrewDryga** [comment]
Another failure is that it doesn't check PLT for some reason:
```
mix dialyzer                                                                                         
In an Umbrella child and no PLT found - building that first.
Finding suitable PLTs
Checking PLT...
[:asn1, :compiler, :connection, :cowboy, :cowlib, :crypto, :db_connection, :decimal, :ecto, :eex, :elixir, :eview, :ex_machina, :hammer_domain, :inets, :jason, :kernel, :libcluster, :logger, :logger_json, :mime, :mix, :phoenix, :phoenix_ecto, :phoenix_pubsub, :plug, :poolboy, :postgrex, :public_key, :ranch, :ssl, :stdlib, :talkinto_domain]
PLT is up to date!
Starting Dialyzer
[
  check_plt: false,
  init_plt: '/Users/andrew/Projects/hammer/mono/_build/dev/dialyxir_erlang-21.0.1_elixir-1.7.0-dev_deps-dev.plt',
  files_rec: ['/Users/andrew/Projects/hammer/mono/_build/dev/lib/talkinto_domain/ebin'],
  warnings: [:unknown],
  explain: nil,
  format: nil,
  raw: nil,
  list: nil
]
:dialyzer.run error: No such file, directory or application: "/Users/andrew/Projects/hammer/mono/_build/dev/dialyxir_erlang-21.0.1_elixir-1.7.0-dev_deps-dev.plt"
```

When running the task with MIX_ENV explicitly works:
```
MIX_ENV=test mix dialyzer                                                                            
In an Umbrella child, not checking PLT...
Starting Dialyzer
[
  check_plt: false,
  init_plt: '/Users/andrew/Projects/hammer/mono/_build/test/dialyxir_erlang-21.0.1_elixir-1.7.0-dev_deps-test.plt',
  files_rec: ['/Users/andrew/Projects/hammer/mono/_build/test/lib/talkinto_domain/ebin'],
  warnings: [:unknown],
  explain: nil,
  format: nil,
  raw: nil,
  list: nil
]
Total errors: 2, Skipped: 0
done in 0m1.74s
:0:unknown_function
Function ExUnit.Callbacks.__merge__/3 does not exist.
________________________________________________________________________________
:0:unknown_function
Function ExUnit.CaseTemplate.__proxy__/2 does not exist.
________________________________________________________________________________
done (warnings were emitted)
```

**Comment by AndrewDryga** [comment]
And here is what happens when I run it with MIX_ENV in the umbrella root:
```
MIX_ENV=test mix dialyzer
No mix project found - checking core PLTs...
Looking up modules in dialyxir_erlang-21.0.1_elixir-1.7.0-dev.plt
Finding applications for dialyxir_erlang-21.0.1_elixir-1.7.0-dev.plt
Finding modules for dialyxir_erlang-21.0.1_elixir-1.7.0-dev.plt
Checking 414 modules in dialyxir_erlang-21.0.1_elixir-1.7.0-dev.plt
```

**Comment by asummers** [comment]
I totally believe that you updated... but that shouldn't be possible on master. What's the output of 

```
cat mix.lock | grep dialyxir
```

?

**Comment by AndrewDryga** [comment]
@asummers sure:
```
 cat mix.lock | grep dialyxir
  "dialyxir": {:git, "https://github.com/jeremyjh/dialyxir.git", "273156eecf597c641567dca0a86ff79e846a8e81", []},
```

**Comment by asummers** [comment]
Intriguing. Thanks.

**Comment by AndrewDryga** [comment]
If you want we can make a short call with screen sharing so I can help with debugging it :)

**Comment by asummers** [comment]
I'll email you if I need to set that up! Hopefully it's unnecessary. Is the best email the one in your profile?

**Comment by jeremyjh** [comment]
That output isn't possible on master. Can you confirm you don't have the task installed in your $MIX_HOME archive?

**Comment by AndrewDryga** [comment]
@jeremyjh that's a great catch, I did have it and it was used when I ran dialyze task from within the project. Sorry guys for taking your time, it was a pretty dumb mistake :).
