### ISSUE TITLE
Protocols for built-in data types

### ISSUE THREAD

**Issue by RobertDober** [jeremyjh/dialyxir#221]
Hello, as requested by @josevalim I would like to report this issue ~https://github.com/eslint/eslint-scope/issues/39~ [corrected below] here.

It has been discussed here https://elixirforum.com/t/dialyzer-listed-not-implemented-protocols-as-unknown-functions/2099.

And here is the project demonstrating the point https://github.com/im-tollu/unhappy_dialyzer.

**Comment by skwerlman** [comment]
seems like there's a copy-paste error in the above post; issue is here: elixir-lang/elixir#7708

**Comment by jeremyjh** [comment]
Thanks for putting all these details together! I agree this needs to be addressed in `dialyxir`.

**Comment by RobertDober** [comment]
@skwerlman thanx for fixing my error

**Comment by asummers** [comment]
Seems like your team had fun with that `eslint` issue yesterday too 😄 😱

**Comment by RobertDober** [comment]
This is strange the error seemed to be fixed in 1.7.1 and reappears in 1.7.2, are you aware of this?
Using 0.5.1

**Comment by gpad** [comment]
@jeremyjh I have the same bug Elixir 1.6 and dialyzer-rc.4

**Comment by asummers** [comment]
@gpad Does this issue occur if you run `mix compile --force` beforehand? Trying to see how it could have been fixed for @RobertDober even though we didn't really explicitly fix things.

**Comment by asummers** [comment]
That's a decent enough workaround for now. But we should fix this here eventually, or provide a flag to do that for you, perhaps? At the very least reference in the README. /cc @jeremyjh

**Comment by gpad** [comment]
@asummers sorry What I mean is that also removing the `_build` the error is still here ...

**Comment by jeremyjh** [comment]
The issue is always going to be there because we do not include the consolidation path in the beam paths. Unless 1.7.1 had a bug where it was putting the consolidated files in the ebin folder I don't see how that could have been "fixed". As Jose noted though, we can't just add that path as then we'll have duplicates we - need to do some kind of merging or diffing of these folders.

**Comment by jeremyjh** [comment]
Dialyxir RC has support Regex ignores. I don't think there is ever a reason to report on a __impl__ function does not exist error. In case you agree, you could solve this forever with something like:

```elixir
# .dialyzer_ignore.exs
[
  ~r/unknown function.*__impl__.*/
]
```

**Comment by gpad** [comment]
@rupurt @jeremyjh I did the same but clearly this is not a _real_ solution ... the probably we should  work with Elixir team to remove the consolidation folder and have everything in a single folder ??

**Comment by jeremyjh** [comment]
Jose already reviewed it, found the issue and assigned it to us and honestly I've not dived in deep enough to suggest compiler changes as an alternative. Right now I think it is fixable in dialyxir and we should do the fix along the lines he suggests. That said, I doubt I'm going to work on it soon so help is wanted.

**Comment by gpad** [comment]
I'll be busy in the next 2 weeks but after I could help you. If anyone can help before ...

**Comment by axelson** [comment]
> Dialyxir RC has support for Regex ignores. I don't think there is ever a reason to report on a `__impl__` function does not exist error. In case you agree, you could solve this forever with something like:
> 
> ```elixir
> # .dialyzer_ignore.exs
> [
>   ~r/unknown function.*__impl__.*/
> ]
> ```

That regex didn't work for me (possibly because `unknown function` is on a different line?

Here is a version that is working for me:
```
[
  ~r/__impl__.*does\ not\ exist\./
]
```

**Comment by amorphid** [comment]
> @gpad I worked around it by adding them to my `.dialyzer_ignore.exs` file:
> 
> ```
> [
>   {":0:unknown_function Function IEx.dont_display_result/0 does not exist.", :unknown_function},
>   {":0:unknown_function Function MyEvent.Atom.__impl__/1 does not exist.",
>    :unknown_function},
>   {":0:unknown_function Function MyEvent.BitString.__impl__/1 does not exist.",
>    :unknown_function},
>   {":0:unknown_function Function MyEvent.Float.__impl__/1 does not exist.",
>    :unknown_function},
>   {":0:unknown_function Function MyEvent.Function.__impl__/1 does not exist.",
>    :unknown_function},
>   {":0:unknown_function Function MyEvent.Integer.__impl__/1 does not exist.",
>    :unknown_function},
>   {":0:unknown_function Function MyEvent.List.__impl__/1 does not exist.",
>    :unknown_function},
>   {":0:unknown_function Function MyEvent.Map.__impl__/1 does not exist.", :unknown_function},
>   {":0:unknown_function Function MyEvent.PID.__impl__/1 does not exist.", :unknown_function},
>   {":0:unknown_function Function MyEvent.Port.__impl__/1 does not exist.",
>    :unknown_function},
>   {":0:unknown_function Function MyEvent.Reference.__impl__/1 does not exist.",
>    :unknown_function},
>   {":0:unknown_function Function MyEvent.Tuple.__impl__/1 does not exist.",
>    :unknown_function}
> ]
> ```

^^^ I like that approach.  I ended up doing this...
```
:ok =
  fn protocol_module -> 
    [
      Atom, 
      BitString, 
      Float, 
      Function, 
      Integer, 
      List, 
      Map, 
      PID, 
      Port, 
      Reference, 
      Tuple
    ]
    |> Enum.each(fn type -> 
      try do 
        _ = Module.concat(protocol_module, type).module_info
      rescue
        _ -> 
          defimpl protocol_module, for: type do
            def to_json(_) do
              raise "encoding not implement for type #{unquote(type)}"
            end
          end
      end
    end)
  end.(<MyProtocolModule>)
```

**Comment by PragTob** [comment]
Just a shoutout that I also just stumbled upon this - would be great to have it fixed but yeah OSS is hard :)

Thanks for all the work :green_heart:

**Comment by ratbag98** [comment]
> ```elixir
>  ~r/unknown function.*__impl__.*/
> ```

underscore, not space, worked for me:

```elixir
~r/unknown_function.*__impl__.*/
```
