### ISSUE TITLE
Unknown error occurred: %Protocol.UndefinedError{protocol: String.Chars, value: {16, 72}, description: ""}

### ISSUE THREAD

**Issue by FelonEkonom** [jeremyjh/dialyxir#563]
```
Please file a bug in https://github.com/jeremyjh/dialyxir/issues with this message.

Unknown error occurred: %Protocol.UndefinedError{protocol: String.Chars, value: {16, 72}, description: ""}


Legacy warning:
lib/mpeg/ts/demuxer.ex:16:72: Unknown type 'Elixir.StreamBuffer':t/0
```

This log was produced by running `mix dialyzer` with the code from this commit: https://github.com/membraneframework-labs/ex_hls/pull/2/commits/9bf42a043ab208dcac5ce29e1ec1b6bb6a7720ee

**Comment by angelikatyborska** [comment]
I started experiencing this error when I migrated the project https://github.com/exercism/elixir/ from Elixir 1.8.1 / OTP 27.2 to Elixir 1.9.1 / OTP 28.1.

The project setup and how dialyzer is run there is pretty weird (there's a dedicated script in `./bin`), but I am sure the error comes from somewhere in this file and appears twice: https://github.com/exercism/elixir/blob/4d760a063565a694319efa57bc7bf6c544943209/exercises/concept/rpg-character-sheet/.meta/exemplar.ex

This is the full output of dialyzer: 

```
Please file a bug in https://github.com/jeremyjh/dialyxir/issues with this message.

Unknown error occurred: %Protocol.UndefinedError{protocol: String.Chars, value: {22, 7}, description: ""}


Legacy warning:
tmp/src/rpg-character-sheet.ex:22:7: Function run/0 has no local return
________________________________________________________________________________
Please file a bug in https://github.com/jeremyjh/dialyxir/issues with this message.

Unknown error occurred: %Protocol.UndefinedError{protocol: String.Chars, value: {34, 8}, description: ""}


Legacy warning:
tmp/src/rpg-character-sheet.ex:34:8: The call 'Elixir.IO':inspect(_character@1::#{'class':=binary(), 'level':=integer(), 'name':=binary()},[{'label', <<89,111,117,114,32,99,104,97,114,97,99,116,101,114>>}]) will never return since it differs in the 2nd argument from the success typing arguments: (any(),[{'base' | 'binaries' | 'charlists' | 'custom_options' | 'inspect_fun' | 'limit' | 'pretty' | 'printable_limit' | 'safe' | 'structs' | 'syntax_colors' | 'width','as_binaries' | 'as_charlists' | 'as_lists' | 'as_strings' | 'binary' | 'decimal' | 'false' | 'hex' | 'infer' | 'infinity' | 'octal' | 'true' | fun((_,map()) -> 'doc_line' | binary() | maybe_improper_list() | {_,_} | {_,_,_} | {_,_,_,_}) | [{_,_}] | non_neg_integer()}])
________________________________________________________________________________
done (warnings were emitted)
Halting VM with exit status 2
```

I noticed how the values in the error `{22, 7}` and `{34, 8}` correspond to the lines of code that trigger the "legacy warnings".

**Comment by jeremyjh** [comment]
@angelikatyborska @FelonEkonom can you try upgrading to the latest release? I think its the same bug fixed in Erlex last week, you'll get that update if you upgrade dialyxir now.

**Comment by angelikatyborska** [comment]
Yes, upgrading to dialyxir 1.4.3 fixed this particular error 🙌 

But I'm still getting a dialyzer warning for my IO.inspect call `IO.inspect(character, label: "Your character")` that should be perfectly valid [according to this type](https://github.com/elixir-lang/elixir/blob/v1.19.2/lib/elixir/lib/io.ex#L131).

```
tmp/src/rpg-character-sheet.ex:34:8:call
The function call will not succeed.

IO.inspect(_character :: %{:class => binary(), :level => integer(), :name => binary()}, [
  {:label, <<89, 111, 117, 114, 32, 99, 104, 97, 114, 97, 99, 116, 101, 114>>}
])

will never return since the 2nd arguments differ
from the success typing arguments:

(any(), [
  {:base
   | :binaries
   | :charlists
   | :custom_options
   | :inspect_fun
   | :limit
   | :pretty
   | :printable_limit
   | :safe
   | :structs
   | :syntax_colors
   | :width,
   :as_binaries
   | :as_charlists
   | :as_lists
   | :as_strings
   | :binary
   | :decimal
   | false
   | :hex
   | :infer
   | :infinity
   | :octal
   | true
   | (_, map() ->
        :doc_line | binary() | maybe_improper_list() | {_, _} | {_, _, _} | {_, _, _, _})
   | [{_, _}]
   | non_neg_integer()}
])
```

Is that something for which I should open a new ticket in this project? Or is it another project's responsibility? 🙂

**Comment by jeremyjh** [comment]
@angelikatyborska the Inspect error was an Elixir bug, IDK if the fix has been released but its in master: https://github.com/elixir-lang/elixir/pull/14865

edit: it was released in 1.19.2: https://github.com/elixir-lang/elixir/releases/tag/v1.19.2

**Comment by angelikatyborska** [comment]
Thank you very much 🎉 that resolved all of the dialyzer issues I had in my project after upgrading to 1.19.
